# This workflow integrates njsscan with GitHub's Code Scanning feature
# nodejsscan is a static security code scanner that finds insecure code patterns in your Node.js applications

name: Security Scan

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '26 18 * * 3'

jobs:
  retirejs:
    runs-on: ubuntu-latest
    name: (retirejs) dependancy scanning
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: retire scan
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install retire
    - run: node_modules/retire/bin/retire
  njsscan:
    runs-on: ubuntu-latest
    name: (njsscan) static code scanning
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '. --sarif --output results.sarif || true'
    - name: Upload njsscan report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
